import { Theme, ThemeId } from '@/types';

export const themes: Record<ThemeId, Theme> = {
    'gold-premium': {
        id: 'gold-premium',
        name: 'Gold Premium',
        emoji: '✨',
        description: 'Elegante, oscuro y dorado',
        bgPrimary: '#0a0a0a',
        bgSecondary: '#111111',
        bgCard: '#1a1a1a',
        textPrimary: '#f5e6c8',
        textSecondary: '#a08050',
        accent: '#d4a843',
        accentSecondary: '#8b6914',
        fontTitle: "'Playfair Display', serif",
        fontBody: "'Inter', sans-serif",
        borderColor: '#3a2e1a',
    },
    superhero: {
        id: 'superhero',
        name: 'Superhéroe',
        emoji: '🦸',
        description: 'Colores fuertes, estilo comic',
        bgPrimary: '#0d1b2a',
        bgSecondary: '#1b263b',
        bgCard: '#1f3a5f',
        textPrimary: '#ffffff',
        textSecondary: '#e0e0e0',
        accent: '#e63946',
        accentSecondary: '#ffd60a',
        fontTitle: "'Bangers', cursive",
        fontBody: "'Nunito', sans-serif",
        borderColor: '#e63946',
    },
    princess: {
        id: 'princess',
        name: 'Princesa',
        emoji: '👑',
        description: 'Pasteles, flores y tiara',
        bgPrimary: '#fff0f3',
        bgSecondary: '#ffe4e8',
        bgCard: '#ffffff',
        textPrimary: '#6d2b3d',
        textSecondary: '#c9748a',
        accent: '#e8527a',
        accentSecondary: '#f9a1bc',
        fontTitle: "'Dancing Script', cursive",
        fontBody: "'Lato', sans-serif",
        borderColor: '#f9a1bc',
    },
    unicorn: {
        id: 'unicorn',
        name: 'Unicornio',
        emoji: '🦄',
        description: 'Tierno, suave y lleno de magia',
        bgPrimary: '#fff0f3',
        bgSecondary: 'rgba(255, 228, 232, 0.4)',
        bgCard: 'rgba(255, 255, 255, 0.8)',
        textPrimary: '#6d2b3d',
        textSecondary: '#c9748a',
        accent: '#e8527a',
        accentSecondary: '#f9a1bc',
        fontTitle: "'Pacifico', cursive",
        fontBody: "'Nunito', sans-serif",
        borderColor: '#f9a1bc',
        bgImage: '/unicorn-rainbow/background.png',
    },
    kpop: {
        id: 'kpop',
        name: 'K-Pop',
        emoji: '🎤',
        description: 'Neones, moderno y audaz',
        bgPrimary: '#0a0a1a',
        bgSecondary: 'rgba(18, 18, 31, 0.6)',
        bgCard: 'rgba(26, 26, 46, 0.75)',
        textPrimary: '#ffffff',
        textSecondary: '#e0e0f0',
        accent: '#fbbf24',
        accentSecondary: '#f472b6',
        fontTitle: "'Black Han Sans', sans-serif",
        fontBody: "'Montserrat', sans-serif",
        borderColor: '#fbbf24',
        bgImage: '/kpop/background.jpg',
    },
    'cyber-neon': {
        id: 'cyber-neon',
        name: 'Cyberpunk Neon',
        emoji: '👁️‍🗨️',
        description: 'Sci-fi, neones y rejillas animadas',
        bgPrimary: '#050505',
        bgSecondary: 'rgba(10, 10, 15, 0.6)',
        bgCard: 'rgba(10, 10, 15, 0.7)',
        textPrimary: '#ffffff',
        textSecondary: '#00f0ff',
        accent: '#ff003c',
        accentSecondary: '#00f0ff',
        fontTitle: "'Orbitron', sans-serif",
        fontBody: "'Space Grotesk', sans-serif",
        borderColor: '#00f0ff',
    },
    'aurora-minimal': {
        id: 'aurora-minimal',
        name: 'Aurora Minimal',
        emoji: '🌌',
        description: 'Degradados dinámicos y glassmorfismo',
        bgPrimary: '#020617',
        bgSecondary: 'rgba(15, 23, 42, 0.5)',
        bgCard: 'rgba(255, 255, 255, 0.05)',
        textPrimary: '#ffffff',
        textSecondary: '#94a3b8',
        accent: '#a855f7',
        accentSecondary: '#3b82f6',
        fontTitle: "'Outfit', sans-serif",
        fontBody: "'Plus Jakarta Sans', sans-serif",
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    'stellar-dark': {
        id: 'stellar-dark',
        name: 'Stellar Dark',
        emoji: '☄️',
        description: 'Estrellas, espacio oscuro y brillos',
        bgPrimary: '#040d21',
        bgSecondary: 'rgba(8, 23, 54, 0.5)',
        bgCard: 'rgba(11, 25, 56, 0.8)',
        textPrimary: '#e2e8f0',
        textSecondary: '#60a5fa',
        accent: '#facc15',
        accentSecondary: '#38bdf8',
        fontTitle: "'Syne', sans-serif",
        fontBody: "'Plus Jakarta Sans', sans-serif",
        borderColor: '#1e3a8a',
    },
    'gamer-neon': {
        id: 'gamer-neon',
        name: 'Gamer Neon',
        emoji: '🎮',
        description: 'Vibrante neón, estilo gaming y esports',
        bgPrimary: '#0f0720',
        bgSecondary: 'rgba(147, 51, 234, 0.15)',
        bgCard: 'rgba(20, 10, 40, 0.8)',
        textPrimary: '#ffffff',
        textSecondary: '#fb923c',
        accent: '#f97316',
        accentSecondary: '#a855f7',
        fontTitle: "'Orbitron', sans-serif",
        fontBody: "'Plus Jakarta Sans', sans-serif",
        borderColor: '#fb923c',
    },
    butterfly: {
        id: 'butterfly',
        name: 'Mariposa Mágica',
        emoji: '🦋',
        description: 'Fondo plateado y púrpura oscuro con destellos',
        bgPrimary: '#05010a',
        bgSecondary: 'rgba(20, 5, 30, 0.75)',
        bgCard: 'rgba(10, 2, 25, 0.8)',
        textPrimary: '#ffffff',
        textSecondary: '#c0c0c0',
        accent: '#b866ff',
        accentSecondary: '#ffffff',
        fontTitle: "'Playfair Display', serif",
        fontBody: "'Montserrat', sans-serif",
        borderColor: 'rgba(255, 255, 255, 0.25)',
        bgImage: '/butterfly/background.png',
    },
    spiderman: {
        id: 'spiderman',
        name: 'Spiderman',
        emoji: '🕷️',
        description: 'Rojo heroico, azul y estilo ciudad urbana',
        bgPrimary: '#0f172a',
        bgSecondary: 'rgba(15, 23, 42, 0.85)',
        bgCard: 'rgba(30, 41, 59, 0.75)',
        textPrimary: '#ffffff',
        textSecondary: '#cbd5e1',
        accent: '#dc2626',
        accentSecondary: '#2563eb',
        fontTitle: "'Bangers', cursive",
        fontBody: "'Montserrat', sans-serif",
        borderColor: '#dc2626',
        bgImage: '/spiderman/background.jpg',
    },
    'goku-ultrainstinto': {
        id: 'goku-ultrainstinto',
        name: 'Goku Ultra Instinto',
        emoji: '🔥',
        description: 'Blanco radiante, plata y azul profundo',
        bgPrimary: '#000000',
        bgSecondary: 'rgba(23, 27, 44, 0.7)',
        bgCard: 'rgba(230, 235, 255, 0.1)',
        textPrimary: '#ffffff',
        textSecondary: '#a5bdf8',
        accent: '#e2e8f0',
        accentSecondary: '#3b82f6',
        fontTitle: "'Bangers', cursive", // Editable via themes
        fontBody: "'Montserrat', sans-serif",
        borderColor: '#94a3b8',
    },
};

export const getTheme = (id: ThemeId): Theme => themes[id] ?? themes['gold-premium'];
